before_script:
  - sh -c 'echo "deb http://apt.roboception.de/stable $DISTRO_CODENAME main" > /etc/apt/sources.list.d/roboception-stable.list'
  - sh -c 'echo "deb http://apt.roboception.de/testing $DISTRO_CODENAME main" > /etc/apt/sources.list.d/roboception-testing.list'
  - curl http://apt.roboception.de/archive.key | apt-key add -
  - apt-get update -yq && apt-get install -y lintian ros-${ROS_DISTRO}-rc-msgs

#############
# Templates
#############

.amd64_template: &amd64_job   # Hidden job that defines an anchor named 'amd64_job'
  image: registry.roboception.de/tools/docker_images:indigo-perception-pcl
  variables:
    DISTRO_CODENAME: trusty
  tags:
    - amd64
    - docker

.armhf_template: &armhf_job   # Hidden job that defines an anchor named 'armhf_job'
  image: registry.roboception.de/tools/docker_images:armhf-indigo-perception
  variables:
    DISTRO_CODENAME: trusty
  tags:
    - armhf
    - docker

.amd64_xenial_template: &amd64_xenial_job
  image: ros:kinetic-perception
  variables:
    DISTRO_CODENAME: xenial
  tags:
    - amd64
    - docker

.armhf_xenial_template: &armhf_xenial_job
  image: registry.roboception.de/tools/docker_images:armhf-kinetic-perception
  variables:
    DISTRO_CODENAME: xenial
  tags:
    - armhf
    - docker

.test_t: &test
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - CTEST_OUTPUT_ON_FAILURE=1 make test

.package_testing_t: &package_testing
  stage: deploy
  script:
    - mkdir build
    - cd build
    - cmake -DCATKIN_BUILD_BINARY_PACKAGE="1" -DCMAKE_INSTALL_PREFIX="/opt/ros/$ROS_DISTRO" -DCMAKE_PREFIX_PATH="/opt/ros/$ROS_DISTRO" -DCMAKE_BUILD_TYPE=Release ..
    - make -j 4
    - make package
    - upload_deb.sh $DISTRO_CODENAME-testing *.deb
  only:
    - master

.package_stable_t: &package_stable
  stage: deploy
  script:
    - mkdir build
    - cd build
    - cmake -DCATKIN_BUILD_BINARY_PACKAGE="1" -DCMAKE_INSTALL_PREFIX="/opt/ros/$ROS_DISTRO" -DCMAKE_PREFIX_PATH="/opt/ros/$ROS_DISTRO" -DCMAKE_BUILD_TYPE=Release ..
    - make -j 4
    - make package
    - upload_deb.sh $DISTRO_CODENAME-stable *.deb
  only:
    - /^v[0-9.]+$/
  except:
    - branches


##############
#### Jobs ####
##############

# Tests (on every commit)
#########################
test_amd64:
  <<: *amd64_job
  <<: *test

test_armhf:
  <<: *armhf_job
  <<: *test

test_xenial_amd64:
  <<: *amd64_xenial_job
  <<: *test

test_xenial_armhf:
  <<: *armhf_xenial_job
  <<: *test

# Deploy testing (only on master)
#################################
package_testing_amd64:
  <<: *amd64_job
  <<: *package_testing

package_testing_armhf:
  <<: *armhf_job
  <<: *package_testing

package_testing_xenial_amd64:
  <<: *amd64_xenial_job
  <<: *package_testing

package_testing_xenial_armhf:
  <<: *armhf_xenial_job
  <<: *package_testing

# Deploy stable (only for releases, version tags)
#################################################
package_stable_amd64:
  <<: *amd64_job
  <<: *package_stable

package_stable_armhf:
  <<: *armhf_job
  <<: *package_stable

package_stable_xenial_amd64:
  <<: *amd64_xenial_job
  <<: *package_stable

package_stable_xenial_armhf:
  <<: *armhf_xenial_job
  <<: *package_stable
